version: '3.3'

services: 
  salt-master:
    hostname: salt-master
    container_name: project_name-salt-master
    image: recondockeradmin/salt-master
    volumes:
        - ~/recon/tv/tvsalt:/srv/salt:rw
        - ~/recon/tv/tvpillar-dev:/srv/pillar:rw
        - ~/recon/tv:/opt/recon/tv:rw

  ddev-core:
    hostname: ddev-core
    container_name: project_name-core
    image: recondockeradmin/ddev-core
    depends_on:
      - salt-master

  ddev-app:
    depends_on:
      - salt-master
    hostname: ddev-app
    image: recondockeradmin/ddev-app
    container_name: project_name-app
    expose: 
      - "80"
      - "443"
    ports:
      #host:container
      - port_1:80"
      - port_2:443"
    volumes:
        - ~/recon/tv/tvapi:/opt/recon/tv/webapp/src/tvapi:rw
        - ~/recon/tv/tvcommon:/opt/recon/tv/webapp/src/tvcommon:rw
        - ~/recon/tv/tvclient:/opt/recon/tv/webapp/src/tvclient:rw
        - ~/recon/tv/ballpark:/opt/recon/tv/webapp/src/ballpark:rw
        - ~/recon/tv/mfgtest:/opt/recon/tv/webapp/src/mfgtest:rw
        - ~/recon/tv/tvwebapp:/opt/recon/tv/webapp/src/tvwebapp:rw
        - ~/recon/tv/python-packages:/opt/recon/tv/webapp/src/python-packages:rw
        - ~/recon/tv/python3-packages:/opt/recon/tv/webapp/src/python3-packages:rw
        - ~/recon/tv/tvproxbox:/opt/recon/tv/proxbox/src/tvproxbox:rw
