version: '3.3'

services:
  salt-master:
    hostname: salt-master
    container_name: salt-master
    image: recondockeradmin/salt-master
    networks:
      - salt-master
    volumes:
        - ~/recon/tv/tvsalt:/srv/salt:rw
        - ~/recon/tv/tvpillar-dev:/srv/pillar:rw
        - ~/recon/tv/:/opt/recon/tv:rw
networks:
  salt-master:
    external: true
